### ISSUE TITLE
Customize base_url

### ISSUE THREAD

**Issue by flyzy2005** [ScrapeGraphAI/Scrapegraph-demo#3]
Could you please add a place to fill in the base_url? Many people access the OpenAI API service not through api.openai.com, but through a proxy server.

**Comment by VinciGit00** [comment]
hi, we added it now

**Comment by flyzy2005** [comment]
Thanks for your consideration. But in the task.py, not None -> not set openai_api_base; None -> set openai_api_base?
```
    if base_url is not None:
        graph_config = {
            "llm": {
                "api_key": key,
                "model": model,
            },
        }
    else: 
        graph_config = {
        "llm": {
            "api_key": key,
            "model": model,
            "openai_api_base": base_url,
        },```
